# -*- coding: utf-8 -*-
"""Ecuador_Satisfacción_Democracia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDvbek08sNTiJUIc8pGfk0lqj5wLLURL

# Data General
"""

# importar todas las librerias
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression

# Leer
df = pd.read_csv('3 Binario (RJ, B, RY).csv') # La BD con los paises

df.info()

df.shape

"""# Extracción de Ecuador"""

df_filtered = df[df['X_23'] == 218]
display(df_filtered.head())

"""Número de filas y columnas después de la extracción"""

df_filtered.shape

"""La variable X_24 corresponde al año. Tener en cuenta la siguiente información:

Codification Years:

2011 -> 16

2013 -> 17

2015 -> 18

2023 -> 23

Años Faltantes:  1995, 1999, 2012, 2014, 2016, 2019, 2021, 2022
"""

unique_x24_count = df_filtered['X_24'].nunique()
print(f"Number of unique values in X_24: {unique_x24_count}")

"""# Extraer solo desde 1998 a 2023 para ECU (df_filtered)"""

df_filtered = df_filtered[~df_filtered['X_24'].isin([1996.0, 1997.0])]

df_filtered.shape

unique_x24_count = df_filtered['X_24'].nunique()
print(f"Number of unique values in X_24: {unique_x24_count}")

"""# Graficos Variables ECU

Gráficos de distribución para cada variable

### A_1: Support for democracy
"""

# Reconstruct df_for_plot with X_24 for plotting from the original df
df_for_plot = df[df['X_23'] == 218].copy()
df_for_plot = df_for_plot[~df_for_plot['X_24'].isin([1996.0, 1997.0])].copy()

# Map coded years to actual years for plotting clarity
year_mapping = {
    16.0: 2011.0,
    17.0: 2013.0,
    18.0: 2015.0,
    23.0: 2023.0
}
df_for_plot['X_24'] = df_for_plot['X_24'].replace(year_mapping)

# Group by year and A_1, then calculate percentages
df_plot_data_A1 = df_for_plot.groupby(['X_24', 'A_1']).size().unstack(fill_value=0)
df_plot_data_A1_percent = df_plot_data_A1.div(df_plot_data_A1.sum(axis=1), axis=0) * 100

# Sort by year to ensure correct temporal order in the plot
df_plot_data_A1_percent = df_plot_data_A1_percent.sort_index()

# Define the full descriptions for A_1 values
a1_descriptions = {
    1: 'Democracy is preferable to any other kind of government',
    2: 'Under some circumstances, an authoritarian government can be preferable to a democratic one',
    3: 'For people like me, it does not matter whether we have a democratic or a non-democratic regime'
}

# Plotting
plt.figure(figsize=(14, 7))

colors = ['blue', 'red', 'green', 'purple', 'orange'] # Define a list of colors for different A_1 values

for i, col in enumerate(df_plot_data_A1_percent.columns):
    # Get the full description for the current A_1 value
    legend_label = a1_descriptions.get(col, f'A_1 {col} (%)') # Fallback if description not found
    plt.plot(df_plot_data_A1_percent.index, df_plot_data_A1_percent[col], marker='o', label=f'{col}: {legend_label}', color=colors[i % len(colors)])
    for x, y in zip(df_plot_data_A1_percent.index, df_plot_data_A1_percent[col]):
        plt.text(x, y + 0.5, f'{y:.1f}%', ha='center', va='bottom', fontsize=9, color=colors[i % len(colors)])

plt.title('Porcentaje de Variable A_1: Support for democracy')
plt.xlabel('Año')
plt.ylabel('Porcentaje de A_1 (%)')
plt.xticks(df_plot_data_A1_percent.index.astype(int), rotation=45) # Show all years as integers
plt.grid(True)
plt.legend(title='Respuestas a Support for democracy', bbox_to_anchor=(0.5, -0.2), loc='upper center', ncol=1, fontsize='medium', title_fontsize='large') # Move legend below the plot and arrange vertically, with custom font sizes
plt.tight_layout()
plt.show()

"""### C_4: Trabajo"""

# Group by year and C_4, then calculate percentages
df_plot_data_C4 = df_for_plot.groupby(['X_24', 'C_4']).size().unstack(fill_value=0)
df_plot_data_C4_percent = df_plot_data_C4.div(df_plot_data_C4.sum(axis=1), axis=0) * 100

# Sort by year to ensure correct temporal order in the plot
df_plot_data_C4_percent = df_plot_data_C4_percent.sort_index()

# Define descriptions for C_4 values (assuming 0 for No, 1 for Yes based on previous plots)
c4_descriptions = {
    0.0: 'No',
    1.0: 'Yes'
}

# Plotting
plt.figure(figsize=(14, 7))

# Use distinct colors for C_4 categories
c_4_colors = {0.0: 'red', 1.0: 'blue'}

for col in df_plot_data_C4_percent.columns:
    legend_label = c4_descriptions.get(col, f'C_4 {int(col)}')
    plt.plot(df_plot_data_C4_percent.index, df_plot_data_C4_percent[col],
             marker='o', label=f'{int(col)}: {legend_label}', color=c_4_colors.get(col))

    # Annotate points with percentage values
    for x, y in zip(df_plot_data_C4_percent.index, df_plot_data_C4_percent[col]):
        if y > 0: # Only annotate if percentage is greater than 0
            plt.text(x, y + 0.5, f'{y:.1f}%', ha='center', va='bottom', fontsize=8, color=c_4_colors.get(col))

plt.title('Percentage of Variable C_4: Employment Situation (Ecuador)')
plt.xlabel('Year')
plt.ylabel('Percentage of C_4 (%)')
plt.xticks(df_plot_data_C4_percent.index.astype(int), rotation=45)
plt.grid(True)
plt.legend(title='Responses to C_4', bbox_to_anchor=(1.05, 0.5), loc='center left', ncol=1,
           fontsize='medium', title_fontsize='large') # Place legend on the right
plt.tight_layout() # Adjust layout to prevent labels/legend from overlapping
plt.show()

"""# Gráfico Etiqueta: Satisfacción con la democracia ECU"""

# Reconstruct df_filtered with X_24 for plotting from the original df
df_for_plot = df[df['X_23'] == 218].copy()
df_for_plot = df_for_plot[~df_for_plot['X_24'].isin([1996.0, 1997.0])].copy()

# Map coded years to actual years for plotting clarity
year_mapping = {
    16.0: 2011.0,
    17.0: 2013.0,
    18.0: 2015.0,
    23.0: 2023.0
}
df_for_plot['X_24'] = df_for_plot['X_24'].replace(year_mapping)

# Group by year and ETIQUETA, then calculate percentages
df_plot_data = df_for_plot.groupby(['X_24', 'ETIQUETA']).size().unstack(fill_value=0)
df_plot_data_percent = df_plot_data.div(df_plot_data.sum(axis=1), axis=0) * 100

# Sort by year to ensure correct temporal order in the plot
df_plot_data_percent = df_plot_data_percent.sort_index()

# Plotting
plt.figure(figsize=(14, 7)) # Increased figure size for better readability of annotations

if 0.0 in df_plot_data_percent.columns:
    plt.plot(df_plot_data_percent.index, df_plot_data_percent[0.0], marker='o', label='ETIQUETA 0 (%)')
    for x, y in zip(df_plot_data_percent.index, df_plot_data_percent[0.0]):
        plt.text(x, y + 0.5, f'{y:.1f}%', ha='center', va='bottom', fontsize=9, color='blue') # Annotate points for ETIQUETA 0

if 1.0 in df_plot_data_percent.columns:
    plt.plot(df_plot_data_percent.index, df_plot_data_percent[1.0], marker='o', label='ETIQUETA 1 (%)')
    for x, y in zip(df_plot_data_percent.index, df_plot_data_percent[1.0]):
        plt.text(x, y - 0.5, f'{y:.1f}%', ha='center', va='top', fontsize=9, color='red') # Annotate points for ETIQUETA 1

plt.title('Porcentaje de ETIQUETA por Año (Ecuador)')
plt.xlabel('Año')
plt.ylabel('Porcentaje de ETIQUETA (%)')
plt.xticks(df_plot_data_percent.index.astype(int), rotation=45) # Show all years as integers
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""# Por Periodos

Primer Periodo: 1998 - 2006 (verificar años) Pre-Correismo

Segundo Periodo: 2007 - 2017 (verificar años) Correísmo

Tercer Periodo: 2018 - 2023 (verificar años) Postcorreismo (años faltantes)

Un año representativo por periodo: 2000, 2013, 2023.

## Preprocesamiento
"""

df_filtered.shape

"""Eliminar las columnas:
A_3: Partidos Políticos, X_23: Country, X_24: Year y X_25: Region
"""

df_period= df_filtered.drop(columns=['A_3', 'X_23', 'X_25'])
# A_3 partidos políticos
# X_23 País: valor único
# X_24 Año se convierte en un periodo
# X_25 Region/Geographical area

cat_cols = ['A_1', 'A_2', 'S_20', 'S_22']
df = pd.get_dummies(df_period, columns=cat_cols, drop_first=True).astype(int)
# A_1 Support for democracy
# A_2 Self positioning on Left-Right Scale
# S_20 Employment Situation
# S_22 Religion

df.shape

"""## Primer Periodo (1998-2006)"""

years_first_period = [1998, 2000, 2001, 2002, 2003, 2004, 2005, 2006]
df_first_period = df[df['X_24'].isin(years_first_period)]
df_first_period = df_first_period.drop('X_24', axis=1)

print("Shape of df_first_period:", df_first_period.shape)

"""### Decision Tree

Data Splitting
"""

# Construction of a function that performs full partitioning
def train_test_splitnew(df, rstate=42, shuffle=True, stratify=None):
    strat = df[stratify] if stratify else None
    train_set, test_set = train_test_split(
        df, test_size=0.2, random_state=rstate, shuffle=shuffle, stratify=strat)
    return (train_set, test_set)

# Asume que 'ETIQUETA' es la columna target
train_set_encoded, test_set_encoded = train_test_splitnew(df_first_period, stratify='ETIQUETA')

# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

"""Definir modelo e hiperparámetros"""

# Modelo base
dt_firstencoded = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_firstencoded = GridSearchCV(
    estimator=dt_firstencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_firstencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_firstencoded = grid_search_dt_firstencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_firstencoded.best_params_.items():
    print(f"{param}: {value}")

"""Resultados"""

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_firstencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_firstencoded.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_firstencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_firstencoded = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_firstencoded = GridSearchCV(
    estimator=rf_firstencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_firstencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_firstencoded = grid_search_rf_firstencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_firstencoded.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_firstencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_firstencoded.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_firstencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regression"""

# Modelo base
lr_periodo1 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_periodo1 = GridSearchCV(
    estimator=lr_periodo1,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_periodo1.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_periodo1 = grid_search_lr_periodo1.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_periodo1.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_periodo1.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

"""## Segundo Periodo (2007-2017)"""

years_second_period = [2007, 2008, 2009, 2010, 16, 17, 18, 2017] # 16 es 2011, 17 es 2013 y 15 es2018
df_second_period = df[df['X_24'].isin(years_second_period)]
df_second_period = df_second_period.drop('X_24', axis=1)

print("Shape of df_second_period:", df_second_period.shape)
#display(df_second_period.head())

"""### Decision Tree

Data Splitting
"""

# Asume que 'ETIQUETA' es la columna target
train_set_encoded, test_set_encoded = train_test_splitnew(df_second_period, stratify='ETIQUETA')

# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

"""Definir modelo y encontrar hiperparámetros"""

# Modelo base
dt_secondencoded = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_secondencoded = GridSearchCV(
    estimator=dt_secondencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_secondencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_secondencoded = grid_search_dt_secondencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_secondencoded.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_secondencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_secondencoded.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_secondencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_secondencoded = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_secondencoded = GridSearchCV(
    estimator=rf_secondencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_secondencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_secondencoded = grid_search_rf_secondencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_secondencoded.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_secondencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_secondencoded.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_secondencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regresion"""

# Modelo base
lr_periodo2 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_periodo2 = GridSearchCV(
    estimator=lr_periodo2,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_periodo2.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_periodo2 = grid_search_lr_periodo2.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_periodo2.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_periodo2.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

"""## Tercer Periodo (2018-2023)"""

years_third_period = [2018, 2020, 23]
df_third_period = df[df['X_24'].isin(years_third_period)]
df_third_period = df_third_period.drop('X_24', axis=1)

print("Shape of df_third_period:", df_third_period.shape)
#display(df_third_period.head())

"""### Decision Tree"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_third_period, stratify='ETIQUETA')
# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Modelo base
dt_thirdencoded = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_thirdencoded = GridSearchCV(
    estimator=dt_thirdencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_thirdencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_thirdencoded = grid_search_dt_thirdencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_thirdencoded.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_thirdencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_thirdencoded.feature_importances_

# Podemos extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_thirdencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_thirdencoded = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_thirdencoded = GridSearchCV(
    estimator=rf_thirdencoded,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_thirdencoded.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_thirdencoded = grid_search_rf_thirdencoded.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_thirdencoded.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_thirdencoded.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_thirdencoded.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_thirdencoded.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regresion"""

# Modelo base
lr_periodo3 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_periodo3 = GridSearchCV(
    estimator=lr_periodo3,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_periodo3.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_periodo3 = grid_search_lr_periodo3.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_periodo3.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_periodo3.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

"""# Año representativo

## 2000
"""

df_2000 = df[df['X_24'] == 2000].copy()
df_2000 = df_2000.drop('X_24', axis=1)

print("Shape of df_2000:", df_2000.shape)

"""### Decision Tree"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2000, stratify='ETIQUETA')
# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Modelo base
dt_2000 = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2000 = GridSearchCV(
    estimator=dt_2000,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2000.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_2000 = grid_search_dt_2000.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2000.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2000.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2000.feature_importances_

# Podemos extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_2000.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_2000 = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_2000 = GridSearchCV(
    estimator=rf_2000,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_2000.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_2000 = grid_search_rf_2000.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_2000.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_2000.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_2000.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_2000.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regresion"""

# Modelo base
lr_2000 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_2000 = GridSearchCV(
    estimator=lr_2000,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_2000.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_2000 = grid_search_lr_2000.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_2000.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_2000.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

"""## 2013"""

df_2013 = df[df['X_24'] == 17].copy()
df_2013 = df_2013.drop('X_24', axis=1)
print("Shape of df_2013:", df_2013.shape)

"""### Decision Tree"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2013, stratify='ETIQUETA')
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Modelo base
dt_2013 = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2013 = GridSearchCV(
    estimator=dt_2013,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2013.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_2013 = grid_search_dt_2013.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2013.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2013.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2013.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_2013.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_2013 = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_2013 = GridSearchCV(
    estimator=rf_2013,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_2013.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_2013 = grid_search_rf_2013.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_2013.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_2013.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_2013.feature_importances_

# Podemos extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_2013.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regresion"""

# Modelo base
lr_2013 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_2013 = GridSearchCV(
    estimator=lr_2013,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_2013.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_2013 = grid_search_lr_2013.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_2013.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_2013.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

"""## 2023"""

df_2023 = df[df['X_24'] == 23].copy()
df_2023 = df_2023.drop('X_24', axis=1)
print("Shape of df_2023:", df_2023.shape)

"""### Decision Tree

"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2023, stratify='ETIQUETA')
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Modelo base
dt_2023 = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2023 = GridSearchCV(
    estimator=dt_2023,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2023.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_dt_model_2023 = grid_search_dt_2023.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2023.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2023.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2023.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_dt_model_2023.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Random Forest"""

# Modelo base
rf_2023 = RandomForestClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10],
    'min_samples_split': [2, 5],
    'max_features': ['sqrt']
}

# Búsqueda de hiperparámetros usando 5-fold CV sobre el TRAIN
grid_search_rf_2023 = GridSearchCV(
    estimator=rf_2023,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar con TRAIN
grid_search_rf_2023.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_rf_model_2023 = grid_search_rf_2013.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_rf_2023.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_rf_model_2023.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_rf_model_2023.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_encoded), best_rf_model_2023.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""### Logistic Regresion"""

# Modelo base
lr_2023 = LogisticRegression(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'liblinear']
}

# Búsqueda de hiperparámetros
grid_search_lr_2023 = GridSearchCV(
    estimator=lr_2023,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenar
grid_search_lr_2023.fit(X_train_encoded, y_train_encoded)

# Mejor modelo
best_lr_model_2023 = grid_search_lr_2023.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_lr_2023.best_params_.items():
    print(f"{param}: {value}")

# Evaluación en TEST
print("Evaluación en conjunto de TEST (Random Forest):")
y_test_pred_encoded = best_lr_model_2023.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

print(best_lr_model_2023.coef_)

feature_importance = pd.DataFrame({
    'Feature': X_train_encoded.columns,
    'Coefficient': best_lr_model_2023.coef_[0]
})

feature_importance = feature_importance.sort_values(
    by='Coefficient',
    ascending=False
)

print(feature_importance)

"""# Data Balanceada

## 2000 DT
"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2000, stratify='ETIQUETA')
# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Instantiate SMOTE
smote = SMOTE(random_state=42)

# Print original class distribution
print("Original class distribution in y_train_encoded:")
print(y_train_encoded.value_counts())

# Apply SMOTE to the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_encoded, y_train_encoded)

# Print new class distribution
print("\nClass distribution after SMOTE:")
print(y_train_resampled.value_counts())

print(f"\nShape of X_train_encoded before SMOTE: {X_train_encoded.shape}")
print(f"Shape of y_train_encoded before SMOTE: {y_train_encoded.shape}")
print(f"Shape of X_train_resampled after SMOTE: {X_train_resampled.shape}")
print(f"Shape of y_train_resampled after SMOTE: {y_train_resampled.shape}")

# Modelo base
dt_2000B = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2000B = GridSearchCV(
    estimator=dt_2000B,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2000B.fit(X_train_resampled, y_train_resampled)

# Mejor modelo
best_dt_model_2000B = grid_search_dt_2000B.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2000B.best_params_.items():
    print(f"{param}: {value}")

print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2000B.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2000B.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_resampled), best_dt_model_2000B.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""## 2013 DT

"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2013, stratify='ETIQUETA')
# Separar X e y para cada subconjunto
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Instantiate SMOTE
smote = SMOTE(random_state=42)

# Print original class distribution
print("Original class distribution in y_train_encoded:")
print(y_train_encoded.value_counts())

# Apply SMOTE to the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_encoded, y_train_encoded)

# Print new class distribution
print("\nClass distribution after SMOTE:")
print(y_train_resampled.value_counts())

print(f"\nShape of X_train_encoded before SMOTE: {X_train_encoded.shape}")
print(f"Shape of y_train_encoded before SMOTE: {y_train_encoded.shape}")
print(f"Shape of X_train_resampled after SMOTE: {X_train_resampled.shape}")
print(f"Shape of y_train_resampled after SMOTE: {y_train_resampled.shape}")

# Modelo base
dt_2013B = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2013B = GridSearchCV(
    estimator=dt_2013B,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2013B.fit(X_train_resampled, y_train_resampled)

# Mejor modelo
best_dt_model_2013B = grid_search_dt_2013B.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2013B.best_params_.items():
    print(f"{param}: {value}")

print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2013B.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2013B.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_resampled), best_dt_model_2013B.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""## 2023 DT"""

train_set_encoded, test_set_encoded = train_test_splitnew(df_2023, stratify='ETIQUETA')
X_train_encoded = train_set_encoded.drop(columns='ETIQUETA')
y_train_encoded = train_set_encoded['ETIQUETA']

X_test_encoded = test_set_encoded.drop(columns='ETIQUETA')
y_test_encoded = test_set_encoded['ETIQUETA']

# Instantiate SMOTE
smote = SMOTE(random_state=42)

# Print original class distribution
print("Original class distribution in y_train_encoded:")
print(y_train_encoded.value_counts())

# Apply SMOTE to the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_encoded, y_train_encoded)

# Print new class distribution
print("\nClass distribution after SMOTE:")
print(y_train_resampled.value_counts())

print(f"\nShape of X_train_encoded before SMOTE: {X_train_encoded.shape}")
print(f"Shape of y_train_encoded before SMOTE: {y_train_encoded.shape}")
print(f"Shape of X_train_resampled after SMOTE: {X_train_resampled.shape}")
print(f"Shape of y_train_resampled after SMOTE: {y_train_resampled.shape}")

# Modelo base
dt_2023B = DecisionTreeClassifier(random_state=42)

# Grid de hiperparámetros
param_grid = {
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy'],
    'max_features': [None, 'sqrt', 'log2']
}

# GridSearchCV sobre el TRAIN
grid_search_dt_2023B = GridSearchCV(
    estimator=dt_2023B,
    param_grid=param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

# Entrenamiento
grid_search_dt_2023B.fit(X_train_resampled, y_train_resampled)

# Mejor modelo
best_dt_model_2023B = grid_search_dt_2023B.best_estimator_

print("Mejores hiperparámetros encontrados:")
for param, value in grid_search_dt_2023B.best_params_.items():
    print(f"{param}: {value}")

print("Evaluación en conjunto de TEST (Decision Tree):")
y_test_pred_encoded = best_dt_model_2023B.predict(X_test_encoded)
print(classification_report(y_test_encoded, y_test_pred_encoded))

best_dt_model_2023B.feature_importances_

# Extraer que características son más importantes para la correcta clasificación de los datos
feature_importances = {name: score for name, score in zip(list(X_train_resampled), best_dt_model_2023B.feature_importances_)}
feature_importances_sorted = pd.Series(feature_importances).sort_values(ascending=False)
feature_importances_sorted.head(5)

"""# Graficos"""

# df_2013 contains data for the year 2013
plt.figure(figsize=(10, 6))
plt.hist(df_2000['S_17'], bins=range(int(df_2000['S_17'].min()), int(df_2000['S_17'].max()) + 2), edgecolor='black')
plt.title('Distribution of Age (S_17) in 2013')
plt.xlabel('Age (S_17)')
plt.ylabel('Frequency')
plt.xticks(range(int(df_2000['S_17'].min()), int(df_2000['S_17'].max()) + 1, 5)) # Adjust x-ticks for better readability
plt.grid(axis='y', alpha=0.75)
plt.show()

# df_2013 contains data for the year 2013
plt.figure(figsize=(10, 6))
plt.hist(df_2013['S_17'], bins=range(int(df_2013['S_17'].min()), int(df_2013['S_17'].max()) + 2), edgecolor='black')
plt.title('Distribution of Age (S_17) in 2013')
plt.xlabel('Age (S_17)')
plt.ylabel('Frequency')
plt.xticks(range(int(df_2013['S_17'].min()), int(df_2013['S_17'].max()) + 1, 5)) # Adjust x-ticks for better readability
plt.grid(axis='y', alpha=0.75)
plt.show()

"""##"""